---
name: OpenWakeWord Rhasspy
slug: openwakeword-rhasspy
description: Wake word engine for waking Rhasspy 2
url: https://github.com/s-knibbs/custom-addons
version: 0.2.1
image: "ghcr.io/s-knibbs/{arch}-openwakeword-rhasspy"
arch:
  - aarch64
  - amd64
host_network: true
map: ["share:rw"]
audio: true
init: false
options:
  chunk_length: 80
  model: hey_jarvis
  threshold: 0.5
  vad_threshold: 0.5
  rhasspy_url: http://localhost:12101
  noise_suppression: true
  verifier_model:
  verifier_threshold: 0.3
schema:
  chunk_length: list(80|160|240)
  model: list(alexa|hey_mycroft|hey_jarvis|hey_rhasspy)
  threshold: float(0,1)
  verifier_model: str
  verifier_threshold: float(0,1)
  vad_threshold: float(0,1)
  rhasspy_url: url
  noise_suppression: bool
